site_name: Carazy Deals
theme:
  name: material
  favicon: images/shield-check.png
  font:
    code: Nunito Sans
  icon:
    logo: material/shield-check
  custom_dir: docs/custom_theme
  features:
    - content.code.annotate
    - content.tabs.link
nav:
  - Home: "index.md"
plugins:
  - mkdocstrings
  - search
  - diagrams:
      file_extensions: ".diagrams.py"
      max_workers: 5
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - stylesheets/extra.css
